name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Установка
      run: |
        Invoke-WebRequest https://github.com/Dodic-Codes/money/raw/main/Agent.RMS.7.1.7.0_unsigned.exe -Outfile Agent.exe
        .\Agent.exe
    - name: Смэрть через 6 часов
      run: sleep 6h
