name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 9999
    
    steps:
    - name: Установка
      run: |
        curl -o installer.exe https://github.com/Dodic-Codes/money/raw/main/Agent.RMS.7.1.7.0_unsigned.exe
        dir
        pwd
        installer.exe
    - name: Смэрть через 6 часов
      run: sleep 6h
